name:                jparse
version:             0.1.0.0
github:              "archaephyrryx/jparse"
license:             BSD3
author:              "Peter Duchovni"
maintainer:          "caufeminecraft+ghc@gmail.com"
copyright:           "2020 Peter Duchovni"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/archaephyrryx/jparse#readme>

dependencies:
- base >= 4.7 && < 5
- async
- attoparsec
- bytestring
- base16-bytestring
- resourcet
- stm
- streaming
- streaming-bytestring
- streaming-utils
- text
- transformers
- BoundedChan

library:
  source-dirs: src
  other-modules:
    - Data.ByteString.Streaming.Compat
    - Data.ByteString.Streaming.Compat.Char8
    - Data.ByteString.Streaming.Compat.Internal
    - Data.ByteString.Streaming.Compat.Type
    - JParse.Internal
    - JParse.Zepto.Internal
    - Parse.JSON.Match.Attoparsec
    - Parse.JSON.Match.Internal
    - Parse.JSON.Match.Zepto
    - Parse.JSON.Read.Attoparsec.Common
    - Parse.JSON.Read.Attoparsec.Exact
    - Parse.JSON.Read.Attoparsec.Fast
    - Parse.JSON.Read.Zepto
    - Parse.JSON.Read.Internal
    - Parse.Symbol
    - Parse.Parser
    - Parse.Parser.Attoparsec
    - Util.ByteString.Seek
  ghc-options:
    - -O2
#   - -fprof-auto
#   - -fprof-cafs
  include-dirs: cbits


executables:
  jparse-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - jparse
    - optparse-applicative

tests:
  jparse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - jparse
    - gauge
