name:                jparse
version:             0.1.0.0
github:              "archaephyrryx/jparse"
license:             BSD3
author:              "Peter Duchovni"
maintainer:          "caufeminecraft+ghc@gmail.com"
copyright:           "2020 Peter Duchovni"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/archaephyrryx/jparse#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- bytestring
- base16-bytestring
- conduit
- streaming
- streaming-bytestring
- text
- transformers

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -fprof-auto
    - -fprof-cafs


executables:
  jparse-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - jparse
    - async
    - optparse-applicative
    - stm
    - vector

tests:
  jparse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - jparse
    - criterion
